import { ArrowDown, ArrowRight, ArrowUp, CheckCircle, Circle, CircleOff, HelpCircle, Timer } from "lucide-react";
import { z } from "zod";

const taskSchema = z.object({
  id: z.string(),
  titleKey: z.string(),
  status: z.string(),
  label: z.string(),
  priority: z.string(),
});

export type Task = z.infer<typeof taskSchema>;

const tasksData = [
  {
    id: "TASK-8782",
    titleKey: "tasks.task8782",
    status: "in progress",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-7878",
    titleKey: "tasks.task7878",
    status: "backlog",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-7839",
    titleKey: "tasks.task7839",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-5562",
    titleKey: "tasks.task5562",
    status: "backlog",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-8686",
    titleKey: "tasks.task8686",
    status: "canceled",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-1280",
    titleKey: "tasks.task1280",
    status: "done",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-7262",
    titleKey: "tasks.task7262",
    status: "done",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-1138",
    titleKey: "tasks.task1138",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7184",
    titleKey: "tasks.task7184",
    status: "todo",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-5160",
    titleKey: "tasks.task5160",
    status: "in progress",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-5618",
    titleKey: "tasks.task5618",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-6699",
    titleKey: "tasks.task6699",
    status: "backlog",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-2858",
    titleKey: "tasks.task2858",
    status: "backlog",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-9864",
    titleKey: "tasks.task9864",
    status: "done",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-8404",
    titleKey: "tasks.task8404",
    status: "in progress",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-5365",
    titleKey: "tasks.task5365",
    status: "in progress",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-1780",
    titleKey: "tasks.task1780",
    status: "todo",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-6938",
    titleKey: "tasks.task6938",
    status: "todo",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-9885",
    titleKey: "tasks.task9885",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-3216",
    titleKey: "tasks.task3216",
    status: "backlog",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-9285",
    titleKey: "tasks.task9285",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-1024",
    titleKey: "tasks.task1024",
    status: "in progress",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-7068",
    titleKey: "tasks.task7068",
    status: "canceled",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-6502",
    titleKey: "tasks.task6502",
    status: "todo",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-5326",
    titleKey: "tasks.task5326",
    status: "todo",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-6274",
    titleKey: "tasks.task6274",
    status: "canceled",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-1571",
    titleKey: "tasks.task1571",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-9518",
    titleKey: "tasks.task9518",
    status: "canceled",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-5581",
    titleKey: "tasks.task5581",
    status: "backlog",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-2197",
    titleKey: "tasks.task2197",
    status: "todo",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-8484",
    titleKey: "tasks.task8484",
    status: "in progress",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-9892",
    titleKey: "tasks.task9892",
    status: "done",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-9616",
    titleKey: "tasks.task9616",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-9744",
    titleKey: "tasks.task9744",
    status: "done",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-1376",
    titleKey: "tasks.task1376",
    status: "backlog",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-7382",
    titleKey: "tasks.task7382",
    status: "todo",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-2290",
    titleKey: "tasks.task2290",
    status: "canceled",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-1533",
    titleKey: "tasks.task1533",
    status: "done",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-4920",
    titleKey: "tasks.task4920",
    status: "in progress",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-5168",
    titleKey: "tasks.task5168",
    status: "in progress",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-7103",
    titleKey: "tasks.task7103",
    status: "canceled",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-4314",
    titleKey: "tasks.task4314",
    status: "in progress",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-3415",
    titleKey: "tasks.task3415",
    status: "todo",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8339",
    titleKey: "tasks.task8339",
    status: "in progress",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-6995",
    titleKey: "tasks.task6995",
    status: "todo",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-8053",
    titleKey: "tasks.task8053",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-4336",
    titleKey: "tasks.task4336",
    status: "todo",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-8790",
    titleKey: "tasks.task8790",
    status: "done",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-8980",
    titleKey: "tasks.task8980",
    status: "canceled",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-7342",
    titleKey: "tasks.task7342",
    status: "backlog",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-5608",
    titleKey: "tasks.task5608",
    status: "canceled",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-1606",
    titleKey: "tasks.task1606",
    status: "done",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7872",
    titleKey: "tasks.task7872",
    status: "canceled",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-4167",
    titleKey: "tasks.task4167",
    status: "canceled",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-9581",
    titleKey: "tasks.task9581",
    status: "backlog",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-8806",
    titleKey: "tasks.task8806",
    status: "done",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-6542",
    titleKey: "tasks.task6542",
    status: "done",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-6806",
    titleKey: "tasks.task6806",
    status: "canceled",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-9549",
    titleKey: "tasks.task9549",
    status: "todo",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-1075",
    titleKey: "tasks.task1075",
    status: "done",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-1427",
    titleKey: "tasks.task1427",
    status: "done",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-1907",
    titleKey: "tasks.task1907",
    status: "todo",
    label: "documentation",
    priority: "high",
  },
  {
    id: "TASK-4309",
    titleKey: "tasks.task4309",
    status: "backlog",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-3973",
    titleKey: "tasks.task3973",
    status: "todo",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-7962",
    titleKey: "tasks.task7962",
    status: "canceled",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-3360",
    titleKey: "tasks.task3360",
    status: "done",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-9887",
    titleKey: "tasks.task9887",
    status: "backlog",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-3649",
    titleKey: "tasks.task3649",
    status: "in progress",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-3586",
    titleKey: "tasks.task3586",
    status: "in progress",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-5150",
    titleKey: "tasks.task5150",
    status: "canceled",
    label: "feature",
    priority: "medium",
  },
  {
    id: "TASK-3652",
    titleKey: "tasks.task3652",
    status: "backlog",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-6884",
    titleKey: "tasks.task6884",
    status: "canceled",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-1591",
    titleKey: "tasks.task1591",
    status: "in progress",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-3802",
    titleKey: "tasks.task3802",
    status: "in progress",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-7253",
    titleKey: "tasks.task7253",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-9739",
    titleKey: "tasks.task9739",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-4424",
    titleKey: "tasks.task4424",
    status: "in progress",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-3922",
    titleKey: "tasks.task3922",
    status: "backlog",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-4921",
    titleKey: "tasks.task4921",
    status: "canceled",
    label: "bug",
    priority: "low",
  },
  {
    id: "TASK-5814",
    titleKey: "tasks.task5814",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-2645",
    titleKey: "tasks.task2645",
    status: "todo",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-4535",
    titleKey: "tasks.task4535",
    status: "in progress",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-4463",
    titleKey: "tasks.task4463",
    status: "done",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-9745",
    titleKey: "tasks.task9745",
    status: "canceled",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-2080",
    titleKey: "tasks.task2080",
    status: "todo",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-3838",
    titleKey: "tasks.task3838",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-1340",
    titleKey: "tasks.task1340",
    status: "todo",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-6665",
    titleKey: "tasks.task6665",
    status: "canceled",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-7585",
    titleKey: "tasks.task7585",
    status: "backlog",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-6319",
    titleKey: "tasks.task6319",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-4369",
    titleKey: "tasks.task4369",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-9035",
    titleKey: "tasks.task9035",
    status: "canceled",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-3970",
    titleKey: "tasks.task3970",
    status: "todo",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-4473",
    titleKey: "tasks.task4473",
    status: "todo",
    label: "documentation",
    priority: "low",
  },
  {
    id: "TASK-4136",
    titleKey: "tasks.task4136",
    status: "canceled",
    label: "bug",
    priority: "medium",
  },
  {
    id: "TASK-3939",
    titleKey: "tasks.task3939",
    status: "done",
    label: "feature",
    priority: "low",
  },
  {
    id: "TASK-2007",
    titleKey: "tasks.task2007",
    status: "backlog",
    label: "bug",
    priority: "high",
  },
  {
    id: "TASK-7516",
    titleKey: "tasks.task7516",
    status: "done",
    label: "documentation",
    priority: "medium",
  },
  {
    id: "TASK-6906",
    titleKey: "tasks.task6906",
    status: "done",
    label: "feature",
    priority: "high",
  },
  {
    id: "TASK-5207",
    titleKey: "tasks.task5207",
    status: "in progress",
    label: "bug",
    priority: "low",
  },
];

export const tasks = z.array(taskSchema).parse(tasksData);

export const labels = [
  {
    value: "bug",
    label: "Bug",
    labelKey: "tasks.labelBug",
  },
  {
    value: "feature",
    label: "Feature",
    labelKey: "tasks.labelFeature",
  },
  {
    value: "documentation",
    label: "Documentation",
    labelKey: "tasks.labelDocumentation",
  },
];

export const statuses = [
  {
    value: "backlog",
    label: "Backlog",
    labelKey: "tasks.statusBacklog",
    icon: HelpCircle,
  },
  {
    value: "todo",
    label: "Todo",
    labelKey: "tasks.statusTodo",
    icon: Circle,
  },
  {
    value: "in progress",
    label: "In Progress",
    labelKey: "tasks.statusInProgress",
    icon: Timer,
  },
  {
    value: "done",
    label: "Done",
    labelKey: "tasks.statusDone",
    icon: CheckCircle,
  },
  {
    value: "canceled",
    label: "Canceled",
    labelKey: "tasks.statusCanceled",
    icon: CircleOff,
  },
];

export const priorities = [
  {
    label: "Low",
    value: "low",
    labelKey: "tasks.priorityLow",
    icon: ArrowDown,
  },
  {
    label: "Medium",
    value: "medium",
    labelKey: "tasks.priorityMedium",
    icon: ArrowRight,
  },
  {
    label: "High",
    value: "high",
    labelKey: "tasks.priorityHigh",
    icon: ArrowUp,
  },
];
