import type { LucideIcon } from "lucide-react";
import { Clock3, Inbox, Mail, MessageCircle, Phone, Send, Star, User } from "lucide-react";

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();
const hoursAgo = (hours: number) => minutesAgo(hours * 60);

export type Conversation = {
  id: number;
  group: "Pinned" | "Today" | "Yesterday";
  name: string;
  subject: string;
  subjectKey: string;
  preview: string;
  previewKey: string;
  time: string;
  isUnread: boolean;
  isOnline: boolean;
  unreadCount: number;
  contact: Contact;
  messages: Message[];
};

export type Message = {
  id: number;
  align: "start" | "end";
  text: string;
  textKey: string;
  time: string;
  reaction?: string;
};

export type Contact = {
  name: string;
  role: string;
  roleKey: string;
  company: string;
  email: string;
  phone: string;
  website: string;
  location: string;
  timezone: string;
  status: string;
  statusKey: string;
  qualifiedAt: string;
  tags: string[];
  tagKeys: string[];
};

export type NavItem = {
  id: string;
  title: string;
  labelKey: string;
  label?: string;
  icon: LucideIcon;
  isActive: boolean;
};

export const navItems: NavItem[] = [
  { id: "inbox", title: "Inbox", labelKey: "chat.navInbox", label: "24", icon: Inbox, isActive: true },
  { id: "mentions", title: "Mentions", labelKey: "chat.navMentions", label: "3", icon: Mail, isActive: false },
  { id: "snoozed", title: "Snoozed", labelKey: "chat.navSnoozed", icon: Clock3, isActive: false },
  { id: "sent", title: "Sent", labelKey: "chat.navSent", icon: Send, isActive: false },
  { id: "all", title: "All conversations", labelKey: "chat.navAllConversations", icon: MessageCircle, isActive: false },
  { id: "unassigned", title: "Unassigned", labelKey: "chat.navUnassigned", label: "7", icon: User, isActive: false },
];

export const channelItems: NavItem[] = [
  { id: "email", title: "Email", labelKey: "chat.channelEmail", label: "18", icon: Mail, isActive: false },
  { id: "chat", title: "Chat", labelKey: "chat.channelChat", label: "5", icon: MessageCircle, isActive: false },
  { id: "whatsapp", title: "WhatsApp", labelKey: "chat.channelWhatsapp", label: "1", icon: Phone, isActive: false },
  { id: "instagram", title: "Instagram", labelKey: "chat.channelInstagram", label: "0", icon: Phone, isActive: false },
  { id: "facebook", title: "Facebook", labelKey: "chat.channelFacebook", label: "0", icon: Phone, isActive: false },
  { id: "phone", title: "Phone", labelKey: "chat.channelPhone", label: "0", icon: Phone, isActive: false },
];

export const viewItems: NavItem[] = [
  { id: "vip", title: "VIP Customers", labelKey: "chat.viewVip", label: "8", icon: Star, isActive: false },
  { id: "orders", title: "Orders & Returns", labelKey: "chat.viewOrders", label: "6", icon: Inbox, isActive: false },
  {
    id: "feedback",
    title: "Product Feedback",
    labelKey: "chat.viewFeedback",
    label: "2",
    icon: MessageCircle,
    isActive: false,
  },
];

export const conversations: Conversation[] = [
  // Pinned
  {
    id: 1,
    group: "Pinned",
    name: "Olivia Rhye",
    subject: "Deployment pipeline failing on staging since last deploy",
    subjectKey: "chat.subjectDeploymentPipeline",
    preview: "We're seeing 502 errors after the latest build went out. Rollback didn't help.",
    previewKey: "chat.previewDeploymentPipeline",
    time: minutesAgo(0),
    isUnread: true,
    isOnline: true,
    unreadCount: 4,
    contact: {
      name: "Olivia Rhye",
      role: "Senior DevOps Engineer",
      roleKey: "chat.roleSeniorDevOpsEngineer",
      company: "Railway Systems Inc.",
      email: "olivia.rhye@weblabs.studio",
      phone: "+1 (415) 555-0123",
      website: "railway.co",
      location: "San Francisco, CA, USA",
      timezone: "PDT (UTC-7)",
      status: "Lead",
      statusKey: "chat.statusLead",
      qualifiedAt: "2026-03-05T12:00:00.000Z",
      tags: ["DevOps", "Enterprise", "P0"],
      tagKeys: ["chat.tagDevOps", "chat.tagEnterprise", "chat.tagP0"],
    },
    messages: [
      {
        id: 101,
        align: "start",
        text: "We're seeing 502s on staging right after the latest build. We rolled back, but the health checks are still red.",
        textKey: "chat.msg101",
        time: minutesAgo(10),
      },
      {
        id: 102,
        align: "end",
        text: "Thanks, Olivia. I'm checking the deploy logs and upstream gateway config now.",
        textKey: "chat.msg102",
        time: minutesAgo(8),
      },
      {
        id: 103,
        align: "start",
        text: "The weird part is API traffic looks fine, but the web container is failing readiness probes.",
        textKey: "chat.msg103",
        time: minutesAgo(5),
      },
      {
        id: 104,
        align: "end",
        text: "Found a mismatch in the staging environment variables. I'm applying the fix and will confirm once the probes recover.",
        textKey: "chat.msg104",
        time: minutesAgo(3),
        reaction: "👍",
      },
      {
        id: 105,
        align: "start",
        text: "Great. Keep me posted, this is blocking our QA pass.",
        textKey: "chat.msg105",
        time: minutesAgo(1),
        reaction: "👀",
      },
    ],
  },
  {
    id: 2,
    group: "Pinned",
    name: "Phoenix Baker",
    subject: "Refund for order #8823 — double charged",
    subjectKey: "chat.subjectRefundDoubleCharge",
    preview: "I was billed twice on the 3rd. Can someone look into this and reverse the duplicate?",
    previewKey: "chat.previewRefundDoubleCharge",
    time: minutesAgo(5),
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Phoenix Baker",
      role: "Operations Lead",
      roleKey: "chat.roleOperationsLead",
      company: "Meridian Retail Group",
      email: "phoenix.baker@weblabs.studio",
      phone: "+1 (312) 555-0184",
      website: "meridianretail.com",
      location: "Chicago, IL, USA",
      timezone: "CDT (UTC-5)",
      status: "Customer",
      statusKey: "chat.statusCustomer",
      qualifiedAt: "2026-01-18T12:00:00.000Z",
      tags: ["Billing", "Enterprise"],
      tagKeys: ["chat.tagBilling", "chat.tagEnterprise"],
    },
    messages: [
      {
        id: 201,
        align: "start",
        text: "I was charged twice for order #8823. One payment cleared on the 3rd and the duplicate posted this morning.",
        textKey: "chat.msg201",
        time: minutesAgo(5),
      },
      {
        id: 202,
        align: "end",
        text: "Thanks for flagging it, Phoenix. I can see both transactions and I'm checking which one was attached to the invoice.",
        textKey: "chat.msg202",
        time: minutesAgo(4),
      },
      {
        id: 203,
        align: "start",
        text: "Please reverse the duplicate if possible. Our finance team is closing the week today.",
        textKey: "chat.msg203",
        time: minutesAgo(3),
      },
      {
        id: 204,
        align: "end",
        text: "The duplicate was a retry from the old payment method. I've started the refund and sent the receipt to your billing email.",
        textKey: "chat.msg204",
        time: minutesAgo(2),
        reaction: "👍",
      },
      {
        id: 205,
        align: "start",
        text: "Perfect, thanks. I'll let finance know to expect it.",
        textKey: "chat.msg205",
        time: minutesAgo(1),
        reaction: "✅",
      },
    ],
  },
  {
    id: 3,
    group: "Pinned",
    name: "Lana Steiner",
    subject: "Access to analytics dashboard — permissions issue",
    subjectKey: "chat.subjectAnalyticsPermissions",
    preview: "I'm getting a 403 since the role update yesterday. Tried clearing cache already.",
    previewKey: "chat.previewAnalyticsPermissions",
    time: minutesAgo(8),
    isUnread: true,
    isOnline: false,
    unreadCount: 2,
    contact: {
      name: "Lana Steiner",
      role: "Data Platform Lead",
      roleKey: "chat.roleDataPlatformLead",
      company: "Monsoon Analytics",
      email: "lana.steiner@acme.inc",
      phone: "+91 98765 43210",
      website: "monsoonanalytics.in",
      location: "Bengaluru, India",
      timezone: "IST (UTC+5:30)",
      status: "Qualified",
      statusKey: "chat.statusQualified",
      qualifiedAt: "2026-04-02T12:00:00.000Z",
      tags: ["IAM", "Enterprise", "High Value"],
      tagKeys: ["chat.tagIam", "chat.tagEnterprise", "chat.tagHighValue"],
    },
    messages: [
      {
        id: 301,
        align: "start",
        text: "I'm getting a 403 on the analytics dashboard since yesterday's role update. Clearing cache did not change anything.",
        textKey: "chat.msg301",
        time: minutesAgo(8),
      },
      {
        id: 302,
        align: "end",
        text: "Thanks, Lana. I'll compare your new role against the dashboard permission set.",
        textKey: "chat.msg302",
        time: minutesAgo(7),
      },
      {
        id: 303,
        align: "start",
        text: "I still have access to exports, just not the dashboard views. Other admins on my team can open them.",
        textKey: "chat.msg303",
        time: minutesAgo(5),
      },
      {
        id: 304,
        align: "end",
        text: "Looks like the Analytics Viewer permission was dropped from your custom role. I've reattached it for your workspace.",
        textKey: "chat.msg304",
        time: minutesAgo(3),
        reaction: "🙌",
      },
      {
        id: 305,
        align: "start",
        text: "That fixed it. Thanks for the quick help.",
        textKey: "chat.msg305",
        time: minutesAgo(1),
        reaction: "🎉",
      },
    ],
  },
  // Today
  {
    id: 5,
    group: "Today",
    name: "Demi Wilkinson",
    subject: "Sustainability report inquiry",
    subjectKey: "chat.subjectSustainabilityReport",
    preview: "Hi team, I'm looking for the latest ESG disclosure for our upcoming board meeting.",
    previewKey: "chat.previewSustainabilityReport",
    time: hoursAgo(2),
    isUnread: true,
    isOnline: true,
    unreadCount: 5,
    contact: {
      name: "Demi Wilkinson",
      role: "Sustainability Manager",
      roleKey: "chat.roleSustainabilityManager",
      company: "BrightFuture Co.",
      email: "demi.wilkinson@weblabs.studio",
      phone: "+1 (415) 555-0189",
      website: "brightfuture.co",
      location: "San Francisco, CA, USA",
      timezone: "PDT (UTC-7)",
      status: "Qualified",
      statusKey: "chat.statusQualified",
      qualifiedAt: "2026-01-22T12:00:00.000Z",
      tags: ["Sustainability", "Enterprise", "FinServ"],
      tagKeys: ["chat.tagSustainability", "chat.tagEnterprise", "chat.tagFinServ"],
    },
    messages: [
      {
        id: 501,
        align: "start",
        text: "Hi, we're preparing board materials and need your latest ESG disclosure, especially the carbon footprint section.",
        textKey: "chat.msg501",
        time: minutesAgo(112),
      },
      {
        id: 502,
        align: "end",
        text: "Hi Demi. I can share the 2025 report and the carbon accounting appendix. Do you need the raw emissions data too?",
        textKey: "chat.msg502",
        time: minutesAgo(108),
      },
      {
        id: 503,
        align: "start",
        text: "Yes, raw Scope 3 data would help. Our board packet needs supply-chain numbers, not just the summary.",
        textKey: "chat.msg503",
        time: minutesAgo(102),
      },
      {
        id: 504,
        align: "end",
        text: "Got it. I'll send the executive summary, Scope 3 CSV, and the methodology note in one bundle.",
        textKey: "chat.msg504",
        time: minutesAgo(98),
        reaction: "👍",
      },
      {
        id: 505,
        align: "start",
        text: "Perfect. That should cover everything for Thursday.",
        textKey: "chat.msg505",
        time: minutesAgo(96),
      },
    ],
  },
  {
    id: 6,
    group: "Today",
    name: "Candice Wu",
    subject: "Bulk export keeps timing out",
    subjectKey: "chat.subjectBulkExportTimeout",
    preview: "Tried three times this morning. It gets to about 60% then throws a gateway error.",
    previewKey: "chat.previewBulkExportTimeout",
    time: hoursAgo(3),
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Candice Wu",
      role: "Data Engineer",
      roleKey: "chat.roleDataEngineer",
      company: "Harbor Ops",
      email: "candice.wu@sandbox.dev",
      phone: "+1 (206) 555-0172",
      website: "harborops.com",
      location: "Seattle, WA, USA",
      timezone: "PDT (UTC-7)",
      status: "Lead",
      statusKey: "chat.statusLead",
      qualifiedAt: "2026-05-10T12:00:00.000Z",
      tags: ["Data", "Performance"],
      tagKeys: ["chat.tagData", "chat.tagPerformance"],
    },
    messages: [
      {
        id: 601,
        align: "start",
        text: "The bulk export keeps timing out. It reaches about 60 percent and then throws a gateway error.",
        textKey: "chat.msg601",
        time: minutesAgo(164),
      },
      {
        id: 602,
        align: "end",
        text: "Thanks, Candice. Is this for the full shipment history export or a filtered date range?",
        textKey: "chat.msg602",
        time: minutesAgo(170),
      },
      {
        id: 603,
        align: "start",
        text: "Full history. We need it for a warehouse migration, so the file is pretty large.",
        textKey: "chat.msg603",
        time: minutesAgo(176),
      },
      {
        id: 604,
        align: "end",
        text: "I'll queue it as an async export and email the download link once it finishes. That avoids the gateway timeout.",
        textKey: "chat.msg604",
        time: minutesAgo(182),
        reaction: "✅",
      },
    ],
  },
  {
    id: 7,
    group: "Today",
    name: "Natali Craig",
    subject: "Invoice INV-4821 still marked unpaid",
    subjectKey: "chat.subjectInvoiceUnpaid",
    preview: "Our payment cleared on Friday — screenshot of the confirmation attached here.",
    previewKey: "chat.previewInvoiceUnpaid",
    time: hoursAgo(4),
    isUnread: true,
    isOnline: false,
    unreadCount: 1,
    contact: {
      name: "Natali Craig",
      role: "Finance Manager",
      roleKey: "chat.roleFinanceManager",
      company: "Lumen Studio",
      email: "natali.craig@weblabs.studio",
      phone: "+39 02 5555 0184",
      website: "lumenstudio.co",
      location: "Milan, Italy",
      timezone: "CEST (UTC+2)",
      status: "Customer",
      statusKey: "chat.statusCustomer",
      qualifiedAt: "2025-10-14T12:00:00.000Z",
      tags: ["Billing", "SMB"],
      tagKeys: ["chat.tagBilling", "chat.tagSMB"],
    },
    messages: [
      {
        id: 701,
        align: "start",
        text: "Invoice INV-4821 still shows unpaid even though our bank transfer cleared last Friday.",
        textKey: "chat.msg701",
        time: minutesAgo(197),
      },
      {
        id: 702,
        align: "end",
        text: "Thanks, Natali. Can you send the transfer reference so I can match it against our payment processor records?",
        textKey: "chat.msg702",
        time: minutesAgo(205),
      },
      {
        id: 703,
        align: "start",
        text: "Just attached the confirmation screenshot. The reference ends in 9147.",
        textKey: "chat.msg703",
        time: minutesAgo(213),
      },
      {
        id: 704,
        align: "end",
        text: "Found it. The payment was received but not reconciled to the invoice. I've marked INV-4821 as paid.",
        textKey: "chat.msg704",
        time: minutesAgo(221),
        reaction: "🙏",
      },
    ],
  },
  {
    id: 8,
    group: "Today",
    name: "Drew Cano",
    subject: "Onboarding docs for new hire — where to start?",
    subjectKey: "chat.subjectOnboardingDocs",
    preview: "Got a new backend dev starting Monday. Need the standard checklist and repo access steps.",
    previewKey: "chat.previewOnboardingDocs",
    time: hoursAgo(5),
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Drew Cano",
      role: "Engineering Manager",
      roleKey: "chat.roleEngineeringManager",
      company: "AtlasWorks",
      email: "drew.cano@internal.tools",
      phone: "+1 (512) 555-0166",
      website: "atlasworks.co",
      location: "Austin, TX, USA",
      timezone: "CDT (UTC-5)",
      status: "Customer",
      statusKey: "chat.statusCustomer",
      qualifiedAt: "2025-08-03T12:00:00.000Z",
      tags: ["Onboarding", "Platform", "NPS Promoter"],
      tagKeys: ["chat.tagOnboarding", "chat.tagPlatform", "chat.tagNpsPromoter"],
    },
    messages: [
      {
        id: 801,
        align: "start",
        text: "We have a backend developer starting Monday. What's the best onboarding path for repo access and environment setup?",
        textKey: "chat.msg801",
        time: minutesAgo(248),
      },
      {
        id: 802,
        align: "end",
        text: "Hi Drew. I'll send the standard engineering checklist and invite link for the developer workspace.",
        textKey: "chat.msg802",
        time: minutesAgo(256),
      },
      {
        id: 803,
        align: "start",
        text: "Great. Please include staging credentials and any branch naming rules if those are documented.",
        textKey: "chat.msg803",
        time: minutesAgo(264),
      },
      {
        id: 804,
        align: "end",
        text: "Will do. I'll add the staging access request and our repository conventions to the same thread.",
        textKey: "chat.msg804",
        time: minutesAgo(271),
        reaction: "👍",
      },
    ],
  },
  {
    id: 9,
    group: "Today",
    name: "Orlando Diggs",
    subject: "Downgrade from Enterprise to Pro plan",
    subjectKey: "chat.subjectDowngradeProPlan",
    preview: "We're winding down the project at end of quarter. Is there an early termination fee?",
    previewKey: "chat.previewDowngradeProPlan",
    time: hoursAgo(6),
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Orlando Diggs",
      role: "CTO",
      roleKey: "chat.roleCto",
      company: "Northstar Workspace",
      email: "orlando.diggs@acme.inc",
      phone: "+1 (720) 555-0195",
      website: "northstarworkspace.com",
      location: "Denver, CO, USA",
      timezone: "MDT (UTC-6)",
      status: "At-Risk",
      statusKey: "chat.statusAtRisk",
      qualifiedAt: "2025-12-01T12:00:00.000Z",
      tags: ["Churn Risk", "Enterprise", "Downgrade"],
      tagKeys: ["chat.tagChurnRisk", "chat.tagEnterprise", "chat.tagDowngrade"],
    },
    messages: [
      {
        id: 901,
        align: "start",
        text: "We're winding down the current project and need to downgrade from Enterprise to Pro at the end of the quarter.",
        textKey: "chat.msg901",
        time: minutesAgo(287),
      },
      {
        id: 902,
        align: "end",
        text: "Understood, Orlando. I can walk through the downgrade path and confirm whether any contract terms apply.",
        textKey: "chat.msg902",
        time: minutesAgo(295),
      },
      {
        id: 903,
        align: "start",
        text: "Main question is whether there is an early termination fee or if we can switch at renewal.",
        textKey: "chat.msg903",
        time: minutesAgo(303),
      },
      {
        id: 904,
        align: "end",
        text: "Your agreement allows downgrade at renewal with 30 days notice. I'll send the date and feature impact summary.",
        textKey: "chat.msg904",
        time: minutesAgo(310),
      },
    ],
  },
  {
    id: 10,
    group: "Today",
    name: "Andi Lane",
    subject: "API rate limit hitting hard during peak",
    subjectKey: "chat.subjectApiRateLimit",
    preview: "Our batch jobs are getting 429s every 15 minutes between 9 and 11 AM. Need a bump.",
    previewKey: "chat.previewApiRateLimit",
    time: hoursAgo(7),
    isUnread: true,
    isOnline: true,
    unreadCount: 3,
    contact: {
      name: "Andi Lane",
      role: "Backend Lead",
      roleKey: "chat.roleBackendLead",
      company: "LedgerLoop",
      email: "andi.lane@weblabs.studio",
      phone: "+353 1 555 0189",
      website: "ledgerloop.io",
      location: "Dublin, Ireland",
      timezone: "IST (UTC+1)",
      status: "Lead",
      statusKey: "chat.statusLead",
      qualifiedAt: "2026-04-19T12:00:00.000Z",
      tags: ["API", "Scaling", "Enterprise"],
      tagKeys: ["chat.tagApi", "chat.tagScaling", "chat.tagEnterprise"],
    },
    messages: [
      {
        id: 1001,
        align: "start",
        text: "Our batch jobs are hitting 429s every few minutes during peak hours. We need a temporary rate limit bump.",
        textKey: "chat.msg1001",
        time: minutesAgo(336),
      },
      {
        id: 1002,
        align: "end",
        text: "Thanks, Andi. Which API keys are affected and what peak window are you seeing?",
        textKey: "chat.msg1002",
        time: minutesAgo(344),
      },
      {
        id: 1003,
        align: "start",
        text: "Mostly invoice-sync and customer-import, between 9 and 11 AM Dublin time.",
        textKey: "chat.msg1003",
        time: minutesAgo(351),
      },
      {
        id: 1004,
        align: "end",
        text: "I can raise the limit for those keys for seven days while we review your long-term quota.",
        textKey: "chat.msg1004",
        time: minutesAgo(359),
      },
    ],
  },
  {
    id: 11,
    group: "Today",
    name: "Kate Morrison",
    subject: "Custom domain SSL cert expired overnight",
    subjectKey: "chat.subjectSslCertExpired",
    preview: "Users are seeing certificate warnings when they hit our shop page. This is urgent.",
    previewKey: "chat.previewSslCertExpired",
    time: hoursAgo(8),
    isUnread: true,
    isOnline: false,
    unreadCount: 6,
    contact: {
      name: "Kate Morrison",
      role: "Product Manager",
      roleKey: "chat.roleProductManager",
      company: "Storefront Labs",
      email: "kate.morrison@weblabs.studio",
      phone: "+1 (213) 555-0192",
      website: "storefrontlabs.com",
      location: "Los Angeles, CA, USA",
      timezone: "PDT (UTC-7)",
      status: "Customer",
      statusKey: "chat.statusCustomer",
      qualifiedAt: "2026-06-02T12:00:00.000Z",
      tags: ["Urgent", "SMB", "SSL"],
      tagKeys: ["chat.tagUrgent", "chat.tagSMB", "chat.tagSsl"],
    },
    messages: [
      {
        id: 1101,
        align: "start",
        text: "Our custom domain started showing certificate warnings overnight. Users cannot complete checkout.",
        textKey: "chat.msg1101",
        time: minutesAgo(418),
      },
      {
        id: 1102,
        align: "end",
        text: "Thanks, Kate. I'm checking the certificate renewal job and DNS validation now.",
        textKey: "chat.msg1102",
        time: minutesAgo(425),
      },
      {
        id: 1103,
        align: "start",
        text: "DNS has not changed on our side. The warning says the certificate expired at midnight.",
        textKey: "chat.msg1103",
        time: minutesAgo(433),
      },
      {
        id: 1104,
        align: "end",
        text: "The renewal job failed on CAA validation. I've reissued the certificate manually and it's propagating.",
        textKey: "chat.msg1104",
        time: minutesAgo(441),
        reaction: "⚡",
      },
    ],
  },
  {
    id: 12,
    group: "Today",
    name: "Alec Whitten",
    subject: "Upgrade to annual billing — is there a discount?",
    subjectKey: "chat.subjectAnnualBilling",
    preview: "We're ready to commit for the year. Can you send over the annual pricing sheet?",
    previewKey: "chat.previewAnnualBilling",
    time: hoursAgo(9),
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Alec Whitten",
      role: "Head of IT",
      roleKey: "chat.roleHeadOfIt",
      company: "Crescent Media Group",
      email: "alec.whitten@internal.tools",
      phone: "+974 4455 1234",
      website: "crescentmedia.qa",
      location: "Doha, Qatar",
      timezone: "AST (UTC+3)",
      status: "Qualified",
      statusKey: "chat.statusQualified",
      qualifiedAt: "2026-05-28T12:00:00.000Z",
      tags: ["Upgrade", "Enterprise", "Media"],
      tagKeys: ["chat.tagUpgrade", "chat.tagEnterprise", "chat.tagMedia"],
    },
    messages: [
      {
        id: 1201,
        align: "start",
        text: "We're ready to move to annual billing. Is there a discount if we commit for the full year?",
        textKey: "chat.msg1201",
        time: minutesAgo(470),
      },
      {
        id: 1202,
        align: "end",
        text: "Hi Alec. Yes, annual billing includes a discount. I can send a quote with the annual terms today.",
        textKey: "chat.msg1202",
        time: minutesAgo(478),
      },
      {
        id: 1203,
        align: "start",
        text: "Please include the media team seats and the analytics add-on in the quote.",
        textKey: "chat.msg1203",
        time: minutesAgo(486),
      },
      {
        id: 1204,
        align: "end",
        text: "Done. I'll include both and mark the quote for annual prepay so procurement can review it quickly.",
        textKey: "chat.msg1204",
        time: minutesAgo(494),
        reaction: "✅",
      },
    ],
  },
  {
    id: 13,
    group: "Today",
    name: "Ariana Decker",
    subject: "Bug: date picker off by one in reports",
    subjectKey: "chat.subjectDatePickerBug",
    preview: "Selecting June 5 produces June 4 in the CSV export. Screenshot attached for reference.",
    previewKey: "chat.previewDatePickerBug",
    time: hoursAgo(10),
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Ariana Decker",
      role: "QA Analyst",
      roleKey: "chat.roleQaAnalyst",
      company: "Northstar Health",
      email: "ariana.decker@weblabs.studio",
      phone: "+1 (617) 555-0188",
      website: "northstarhealth.com",
      location: "Boston, MA, USA",
      timezone: "EDT (UTC-4)",
      status: "Customer",
      statusKey: "chat.statusCustomer",
      qualifiedAt: "2026-03-14T12:00:00.000Z",
      tags: ["Bug", "Reports"],
      tagKeys: ["chat.tagBug", "chat.tagReports"],
    },
    messages: [
      {
        id: 1301,
        align: "start",
        text: "The report date picker is off by one. Selecting June 5 exports June 4 in the CSV.",
        textKey: "chat.msg1301",
        time: minutesAgo(560),
      },
      {
        id: 1302,
        align: "end",
        text: "Thanks, Ariana. Does the UI show the right date before export, or is it wrong there too?",
        textKey: "chat.msg1302",
        time: minutesAgo(568),
      },
      {
        id: 1303,
        align: "start",
        text: "The UI looks correct. Only the CSV output is shifted.",
        textKey: "chat.msg1303",
        time: minutesAgo(576),
      },
      {
        id: 1304,
        align: "end",
        text: "That points to timezone conversion in the export job. I'll attach your screenshot to the bug ticket.",
        textKey: "chat.msg1304",
        time: minutesAgo(583),
      },
    ],
  },
  {
    id: 14,
    group: "Today",
    name: "Steven Tey",
    subject: "Webhook delivery failures for Zapier integration",
    subjectKey: "chat.subjectWebhookFailures",
    preview: "Getting intermittent 500s on the webhook endpoint since roughly 2 AM UTC. Logs linked.",
    previewKey: "chat.previewWebhookFailures",
    time: hoursAgo(11),
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Steven Tey",
      role: "Solutions Architect",
      roleKey: "chat.roleSolutionsArchitect",
      company: "BridgeWork Inc.",
      email: "steven.tey@sandbox.dev",
      phone: "+1 (404) 555-0141",
      website: "bridgework.io",
      location: "Atlanta, GA, USA",
      timezone: "EDT (UTC-4)",
      status: "Lead",
      statusKey: "chat.statusLead",
      qualifiedAt: "2026-04-08T12:00:00.000Z",
      tags: ["Integrations", "Platform", "Zapier"],
      tagKeys: ["chat.tagIntegrations", "chat.tagPlatform", "chat.tagZapier"],
    },
    messages: [
      {
        id: 1401,
        align: "start",
        text: "Zapier webhook delivery is failing intermittently with 500s. It started around 2 AM UTC.",
        textKey: "chat.msg1401",
        time: minutesAgo(642),
      },
      {
        id: 1402,
        align: "end",
        text: "Thanks, Steven. Can you share one failed delivery ID and the endpoint path?",
        textKey: "chat.msg1402",
        time: minutesAgo(650),
      },
      {
        id: 1403,
        align: "start",
        text: "Delivery ID wh_72a9. Endpoint is /hooks/zapier/customer-created.",
        textKey: "chat.msg1403",
        time: minutesAgo(658),
      },
      {
        id: 1404,
        align: "end",
        text: "I found retries backing up on that endpoint. We're increasing worker capacity and replaying the failed deliveries.",
        textKey: "chat.msg1404",
        time: minutesAgo(665),
      },
    ],
  },
  {
    id: 15,
    group: "Today",
    name: "Lori Bryson",
    subject: "Request: granular RBAC for team leads",
    subjectKey: "chat.subjectGranularRbac",
    preview: "Our engineering leads need read-only on production but full write access on staging.",
    previewKey: "chat.previewGranularRbac",
    time: hoursAgo(12),
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Lori Bryson",
      role: "Platform Architect",
      roleKey: "chat.rolePlatformArchitect",
      company: "KumoWorks K.K.",
      email: "lori.bryson@acme.inc",
      phone: "+81 3 5555 0173",
      website: "kumoworks.jp",
      location: "Tokyo, Japan",
      timezone: "JST (UTC+9)",
      status: "Qualified",
      statusKey: "chat.statusQualified",
      qualifiedAt: "2026-02-09T12:00:00.000Z",
      tags: ["RBAC", "Enterprise", "Feature Request"],
      tagKeys: ["chat.tagRbac", "chat.tagEnterprise", "chat.tagFeatureRequest"],
    },
    messages: [
      {
        id: 1501,
        align: "start",
        text: "Our team leads need read-only production access but full write permissions in staging. Can RBAC support that split?",
        textKey: "chat.msg1501",
        time: minutesAgo(693),
      },
      {
        id: 1502,
        align: "end",
        text: "Yes, Lori. You can separate environment scope from permission level. I'll send the policy example.",
        textKey: "chat.msg1502",
        time: minutesAgo(700),
      },
      {
        id: 1503,
        align: "start",
        text: "Great. We also need audit logs to show who changed staging configs.",
        textKey: "chat.msg1503",
        time: minutesAgo(708),
      },
      {
        id: 1504,
        align: "end",
        text: "That is included. I'll add the audit log filters to the example so your leads can test it.",
        textKey: "chat.msg1504",
        time: minutesAgo(716),
      },
    ],
  },
  {
    id: 16,
    group: "Today",
    name: "Koray Okumus",
    subject: "Mobile app crashes on Android 14 after update",
    subjectKey: "chat.subjectAndroidCrash",
    preview: "Three users reported the same crash on launch. Stack trace from Firebase attached.",
    previewKey: "chat.previewAndroidCrash",
    time: hoursAgo(13),
    isUnread: true,
    isOnline: false,
    unreadCount: 3,
    contact: {
      name: "Koray Okumus",
      role: "Mobile Lead",
      roleKey: "chat.roleMobileLead",
      company: "MobiSolar Ltd.",
      email: "koray.okumus@weblabs.studio",
      phone: "+254 711 555 0182",
      website: "mobisolar.co.ke",
      location: "Nairobi, Kenya",
      timezone: "EAT (UTC+3)",
      status: "Customer",
      statusKey: "chat.statusCustomer",
      qualifiedAt: "2026-01-05T12:00:00.000Z",
      tags: ["Mobile", "Android", "Bug"],
      tagKeys: ["chat.tagMobile", "chat.tagAndroid", "chat.tagBug"],
    },
    messages: [
      {
        id: 1601,
        align: "start",
        text: "Our Android users on version 14 are seeing crashes right after the splash screen. Firebase shows three affected devices so far.",
        textKey: "chat.msg1601",
        time: minutesAgo(743),
      },
      {
        id: 1602,
        align: "end",
        text: "Thanks for reporting this, Koray. Can you share the Firebase crashlytics link? I'll get the mobile team on it.",
        textKey: "chat.msg1602",
        time: minutesAgo(769),
      },
      {
        id: 1603,
        align: "start",
        text: "Sure, linked the stack trace in the ticket. Looks like a null pointer in the payment module init.",
        textKey: "chat.msg1603",
        time: minutesAgo(794),
      },
      {
        id: 1604,
        align: "end",
        text: "Found it — there's an edge case when Google Play Services isn't updated. We're pushing a hotfix now.",
        textKey: "chat.msg1604",
        time: minutesAgo(818),
      },
    ],
  },
  // Yesterday
  {
    id: 17,
    group: "Yesterday",
    name: "Josh Miller",
    subject: "Partnership proposal for Latin American market",
    subjectKey: "chat.subjectLatamPartnership",
    preview: "We're expanding into Mexico and Brazil next quarter. Would love to explore a reseller deal.",
    previewKey: "chat.previewLatamPartnership",
    time: hoursAgo(26),
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Josh Miller",
      role: "CEO",
      roleKey: "chat.roleCeo",
      company: "Nexo Digital MX",
      email: "josh.miller@internal.tools",
      phone: "+52 55 5555 0165",
      website: "nexodigital.mx",
      location: "Mexico City, Mexico",
      timezone: "CST (UTC-6)",
      status: "Lead",
      statusKey: "chat.statusLead",
      qualifiedAt: "2026-05-15T12:00:00.000Z",
      tags: ["Partnership", "LATAM", "Reseller"],
      tagKeys: ["chat.tagPartnership", "chat.tagLatam", "chat.tagReseller"],
    },
    messages: [
      {
        id: 1701,
        align: "start",
        text: "We're expanding into Mexico and Brazil next quarter and want to explore a reseller partnership.",
        textKey: "chat.msg1701",
        time: hoursAgo(26),
      },
      {
        id: 1702,
        align: "end",
        text: "Thanks, Josh. That sounds aligned with our LATAM plans. Do you already have target customer segments in mind?",
        textKey: "chat.msg1702",
        time: hoursAgo(26),
      },
      {
        id: 1703,
        align: "start",
        text: "Mostly mid-market logistics and retail teams. We can bring initial pipeline if the reseller terms work.",
        textKey: "chat.msg1703",
        time: hoursAgo(26),
      },
      {
        id: 1704,
        align: "end",
        text: "I'll introduce you to our partnerships lead and share the reseller tier overview before Friday.",
        textKey: "chat.msg1704",
        time: hoursAgo(26),
      },
    ],
  },
  {
    id: 18,
    group: "Yesterday",
    name: "Mollie Hall",
    subject: "Data export — need all logs from May",
    subjectKey: "chat.subjectMayLogsExport",
    preview: "Our compliance audit starts next week. I need a full activity log dump for the auditors.",
    previewKey: "chat.previewMayLogsExport",
    time: hoursAgo(26),
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Mollie Hall",
      role: "Compliance Officer",
      roleKey: "chat.roleComplianceOfficer",
      company: "NovaPay Ltd.",
      email: "mollie.hall@weblabs.studio",
      phone: "+44 20 5555 0178",
      website: "novapay.co.uk",
      location: "London, UK",
      timezone: "BST (UTC+1)",
      status: "Customer",
      statusKey: "chat.statusCustomer",
      qualifiedAt: "2025-11-08T12:00:00.000Z",
      tags: ["Compliance", "FinServ", "Audit"],
      tagKeys: ["chat.tagCompliance", "chat.tagFinServ", "chat.tagAudit"],
    },
    messages: [
      {
        id: 1801,
        align: "start",
        text: "Our compliance audit starts next week. We need activity logs for all May workspace events.",
        textKey: "chat.msg1801",
        time: hoursAgo(26),
      },
      {
        id: 1802,
        align: "end",
        text: "Hi Mollie. We can export admin activity, login events, and file access logs. Do auditors need CSV or JSON?",
        textKey: "chat.msg1802",
        time: hoursAgo(26),
      },
      {
        id: 1803,
        align: "start",
        text: "CSV is fine, but it needs user IDs and timestamps in UTC.",
        textKey: "chat.msg1803",
        time: hoursAgo(26),
      },
      {
        id: 1804,
        align: "end",
        text: "Understood. I'll prepare the May export with UTC timestamps and send it through the secure file link.",
        textKey: "chat.msg1804",
        time: hoursAgo(26),
      },
    ],
  },
  {
    id: 19,
    group: "Yesterday",
    name: "Rene Wells",
    subject: "White-label options for our reseller program",
    subjectKey: "chat.subjectWhiteLabelOptions",
    preview: "We have five partners asking about branded dashboards. Do you offer white-label tiers?",
    previewKey: "chat.previewWhiteLabelOptions",
    time: hoursAgo(26),
    isUnread: true,
    isOnline: true,
    unreadCount: 1,
    contact: {
      name: "Rene Wells",
      role: "Product Director",
      roleKey: "chat.roleProductDirector",
      company: "Jambo Digital KE",
      email: "rene.wells@acme.inc",
      phone: "+254 722 555 0194",
      website: "jambodigital.ke",
      location: "Nairobi, Kenya",
      timezone: "EAT (UTC+3)",
      status: "Qualified",
      statusKey: "chat.statusQualified",
      qualifiedAt: "2026-04-25T12:00:00.000Z",
      tags: ["White-Label", "Reseller", "Platform"],
      tagKeys: ["chat.tagWhiteLabel", "chat.tagReseller", "chat.tagPlatform"],
    },
    messages: [
      {
        id: 1901,
        align: "start",
        text: "We have five reseller partners asking whether the dashboard can be white-labeled.",
        textKey: "chat.msg1901",
        time: hoursAgo(26),
      },
      {
        id: 1902,
        align: "end",
        text: "Hi Rene. White-labeling is available on the partner tier. Are they asking about custom domain, logo, or full theme control?",
        textKey: "chat.msg1902",
        time: hoursAgo(26),
      },
      {
        id: 1903,
        align: "start",
        text: "All three, ideally. They want their own domain and branded reports for clients.",
        textKey: "chat.msg1903",
        time: hoursAgo(26),
      },
      {
        id: 1904,
        align: "end",
        text: "That is supported. I'll send the partner tier doc and a sample branded report template.",
        textKey: "chat.msg1904",
        time: hoursAgo(26),
      },
    ],
  },
  {
    id: 20,
    group: "Yesterday",
    name: "Rylee Howard",
    subject: "MFA enforcement rollout — questions",
    subjectKey: "chat.subjectMfaEnforcement",
    preview: "Our security team wants to know if SMS fallback is still supported after the enforcement date.",
    previewKey: "chat.previewMfaEnforcement",
    time: hoursAgo(26),
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Rylee Howard",
      role: "Security Architect",
      roleKey: "chat.roleSecurityArchitect",
      company: "Grupo Financiero Sur",
      email: "rylee.howard@sandbox.dev",
      phone: "+57 601 555 0180",
      website: "gfsur.com.co",
      location: "Bogotá, Colombia",
      timezone: "COT (UTC-5)",
      status: "Qualified",
      statusKey: "chat.statusQualified",
      qualifiedAt: "2026-03-30T12:00:00.000Z",
      tags: ["Security", "Enterprise", "MFA"],
      tagKeys: ["chat.tagSecurity", "chat.tagEnterprise", "chat.tagMfa"],
    },
    messages: [
      {
        id: 2001,
        align: "start",
        text: "Our security team has questions about the MFA enforcement rollout. Is SMS fallback still supported?",
        textKey: "chat.msg2001",
        time: hoursAgo(26),
      },
      {
        id: 2002,
        align: "end",
        text: "Hi Rylee. SMS fallback remains available, but we recommend authenticator apps or security keys for admins.",
        textKey: "chat.msg2002",
        time: hoursAgo(26),
      },
      {
        id: 2003,
        align: "start",
        text: "Can we enforce security keys for admins and allow SMS only for contractors?",
        textKey: "chat.msg2003",
        time: hoursAgo(26),
      },
      {
        id: 2004,
        align: "end",
        text: "Yes. You can configure that by user group. I'll send the policy setup steps.",
        textKey: "chat.msg2004",
        time: hoursAgo(26),
      },
    ],
  },
  {
    id: 21,
    group: "Yesterday",
    name: "Sienna Hewitt",
    subject: "Missing line items in CSV export",
    subjectKey: "chat.subjectMissingLineItems",
    preview: "The January invoice export is short by three line items. The PDF version is correct though.",
    previewKey: "chat.previewMissingLineItems",
    time: hoursAgo(26),
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Sienna Hewitt",
      role: "Finance Director",
      roleKey: "chat.roleFinanceDirector",
      company: "Volta Energy AB",
      email: "sienna.hewitt@weblabs.studio",
      phone: "+46 73 555 0168",
      website: "voltaenergy.se",
      location: "Malmö, Sweden",
      timezone: "CEST (UTC+2)",
      status: "Customer",
      statusKey: "chat.statusCustomer",
      qualifiedAt: "2025-09-12T12:00:00.000Z",
      tags: ["Billing", "Export", "Bug"],
      tagKeys: ["chat.tagBilling", "chat.tagExport", "chat.tagBug"],
    },
    messages: [
      {
        id: 2101,
        align: "start",
        text: "The January invoice CSV is missing three line items. The PDF invoice looks correct.",
        textKey: "chat.msg2101",
        time: hoursAgo(26),
      },
      {
        id: 2102,
        align: "end",
        text: "Thanks, Sienna. Are the missing line items discounts, usage charges, or taxes?",
        textKey: "chat.msg2102",
        time: hoursAgo(26),
      },
      {
        id: 2103,
        align: "start",
        text: "Two are usage charges and one is a tax adjustment. They all appear in the PDF.",
        textKey: "chat.msg2103",
        time: hoursAgo(26),
      },
      {
        id: 2104,
        align: "end",
        text: "I found an export filter excluding adjusted usage lines. We'll patch it and regenerate the January CSV for you.",
        textKey: "chat.msg2104",
        time: hoursAgo(26),
      },
    ],
  },
  {
    id: 22,
    group: "Yesterday",
    name: "Noah Pierre",
    subject: "Demo request for procurement team — Friday",
    subjectKey: "chat.subjectProcurementDemo",
    preview: "Need a 30-minute walkthrough of the vendor portal for our finance leads this Friday.",
    previewKey: "chat.previewProcurementDemo",
    time: hoursAgo(26),
    isUnread: true,
    isOnline: false,
    unreadCount: 5,
    contact: {
      name: "Noah Pierre",
      role: "Procurement Manager",
      roleKey: "chat.roleProcurementManager",
      company: "First Atlantic Bank NG",
      email: "noah.pierre@weblabs.studio",
      phone: "+234 805 555 0125",
      website: "firstatlanticbank.ng",
      location: "Abuja, Nigeria",
      timezone: "WAT (UTC+1)",
      status: "Lead",
      statusKey: "chat.statusLead",
      qualifiedAt: "2026-05-20T12:00:00.000Z",
      tags: ["Demo", "FinServ", "Enterprise"],
      tagKeys: ["chat.tagDemo", "chat.tagFinServ", "chat.tagEnterprise"],
    },
    messages: [
      {
        id: 2201,
        align: "start",
        text: "Could we schedule a 30-minute demo for our procurement and finance leads this Friday?",
        textKey: "chat.msg2201",
        time: hoursAgo(26),
      },
      {
        id: 2202,
        align: "end",
        text: "Absolutely, Noah. Should the walkthrough focus on vendor onboarding, approvals, or reporting?",
        textKey: "chat.msg2202",
        time: hoursAgo(26),
      },
      {
        id: 2203,
        align: "start",
        text: "Vendor onboarding and approval routing are the priority. Reporting can be a quick overview.",
        textKey: "chat.msg2203",
        time: hoursAgo(26),
      },
      {
        id: 2204,
        align: "end",
        text: "Great. I'll send a Friday slot with an agenda tailored to those two workflows.",
        textKey: "chat.msg2204",
        time: hoursAgo(26),
      },
    ],
  },
  {
    id: 23,
    group: "Yesterday",
    name: "Eve Lechner",
    subject: "SSO integration with Azure AD",
    subjectKey: "chat.subjectAzureSso",
    preview: "We're migrating from Okta to Azure AD. What's the typical setup timeline for SSO?",
    previewKey: "chat.previewAzureSso",
    time: hoursAgo(26),
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Eve Lechner",
      role: "IT Director",
      roleKey: "chat.roleItDirector",
      company: "Northlane IT",
      email: "eve.lechner@acme.inc",
      phone: "+420 222 555 013",
      website: "northlaneit.com",
      location: "Prague, Czechia",
      timezone: "CEST (UTC+2)",
      status: "Qualified",
      statusKey: "chat.statusQualified",
      qualifiedAt: "2026-02-14T12:00:00.000Z",
      tags: ["SSO", "Azure", "Enterprise"],
      tagKeys: ["chat.tagSso", "chat.tagAzure", "chat.tagEnterprise"],
    },
    messages: [
      {
        id: 2301,
        align: "start",
        text: "We're moving from Okta to Azure AD and need to understand the SSO setup timeline.",
        textKey: "chat.msg2301",
        time: hoursAgo(26),
      },
      {
        id: 2302,
        align: "end",
        text: "Hi Eve. Typical Azure AD SSO setup takes one to two business days once metadata is exchanged.",
        textKey: "chat.msg2302",
        time: hoursAgo(26),
      },
      {
        id: 2303,
        align: "start",
        text: "We can share metadata today. Will there be downtime during the switch?",
        textKey: "chat.msg2303",
        time: hoursAgo(26),
      },
      {
        id: 2304,
        align: "end",
        text: "No downtime if we test with a pilot group first. I'll send the Azure AD checklist and rollout plan.",
        textKey: "chat.msg2304",
        time: hoursAgo(26),
      },
    ],
  },
  {
    id: 24,
    group: "Yesterday",
    name: "Zahir McClure",
    subject: "Cancellation request — account owner left",
    subjectKey: "chat.subjectCancellationRequest",
    preview: "Our ops lead resigned last week. Need to transfer ownership to me before we can cancel.",
    previewKey: "chat.previewCancellationRequest",
    time: hoursAgo(26),
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Zahir McClure",
      role: "Operations Director",
      roleKey: "chat.roleOperationsDirector",
      company: "Cedar Grove Ventures",
      email: "zahir.mcclure@internal.tools",
      phone: "+1 (615) 555-0175",
      website: "cedargrove.vc",
      location: "Nashville, TN, USA",
      timezone: "CDT (UTC-5)",
      status: "At-Risk",
      statusKey: "chat.statusAtRisk",
      qualifiedAt: "2025-06-15T12:00:00.000Z",
      tags: ["Churn Risk", "Account", "SMB"],
      tagKeys: ["chat.tagChurnRisk", "chat.tagAccount", "chat.tagSMB"],
    },
    messages: [
      {
        id: 2401,
        align: "start",
        text: "Our ops lead Jamal resigned last week and he was the only account owner. I need ownership transferred to me before we can proceed with anything.",
        textKey: "chat.msg2401",
        time: hoursAgo(26),
      },
      {
        id: 2402,
        align: "end",
        text: "Hi Zahir, I can help with that. We'll need verification — can you confirm your role and provide a copy of Jamal's resignation notice?",
        textKey: "chat.msg2402",
        time: hoursAgo(26),
      },
      {
        id: 2403,
        align: "start",
        text: "Absolutely. I'm the Operations Director. I've attached his signed notice and HR confirmation.",
        textKey: "chat.msg2403",
        time: hoursAgo(26),
      },
      {
        id: 2404,
        align: "end",
        text: "Verified. I've initiated the ownership transfer. It takes about 2 hours to propagate. You'll get a confirmation email once it's done.",
        textKey: "chat.msg2404",
        time: hoursAgo(26),
      },
    ],
  },
];

export const currentUser = {
  name: "Arham Khan",
  email: "arham.khan@weblabs.studio",
};
